# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Top100' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Top100
  pod 'RealmSwift', '~>10'

  target 'Top100Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Top100UITests' do
    # Pods for testing
  end

end
